fix(AP-2793): add coexistence mode with asset-manager (#40)
* fix(AP-2793): add coexistence mode with asset-manager

Adds ability for a server-side rendered page, such as one using the NextJS SDK, to indicate that it will be responsible for instantiating the Evolv client

In particular this prevents the occurrence of the following error:
```
TypeError: Cannot set property client of #<Object> which has only a getter
```

* docs(AP-2793): add documentation for coexistence mode

* ci(AP-2793): publish using commit from "tag" job